<?php
/**
 * +----------------------------------------------------------------------
 * | 九月科技-ztuc.cn
 * +----------------------------------------------------------------------
 *                      .::::.
 *                    .::::::::.            | AUTHOR: siyu
 *                    :::::::::::           | EMAIL: ztucke@ztuc.cn
 *                 ..:::::::::::'           | DATETIME: 2020/01/31
 *             '::::::::::::'
 *                .::::::::::
 *           '::::::::::::::..
 *                ..::::::::::::.
 *              ``::::::::::::::::
 *               ::::``:::::::::'        .:::.
 *              ::::'   ':::::'       .::::::::.
 *            .::::'      ::::     .:::::::'::::.
 *           .:::'       :::::  .:::::::::' ':::::.
 *          .::'        :::::.:::::::::'      ':::::.
 *         .::'         ::::::::::::::'         ``::::.
 *     ...:::           ::::::::::::'              ``::.
 *   ```` ':.          ':::::::::'                  ::::..
 *                      '.:::::'                    ':'````..
 * +----------------------------------------------------------------------
 */
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/3/10
 * Time: 20:39
 */
namespace app\controller\core;

use app\BaseController;
use app\model\admin\AdminLog;
use app\model\admin\Banner;
use app\model\admin\User;
use think\facade\Session;
use app\model\admin\Admin;
use think\facade\View;
use think\facade\Cookie;
use app\model\admin\Category;
use app\controller\index\Index;
use app\model\admin\Sidebar;
use app\model\admin\AuthGroup;
/**
 * 核心控制器
 * Class InitController
 * @package app\controller\core
 */
class InitController extends BaseController
{
    use TraitFormer;

    // 后台管理员信息
    protected $admin = null;

    // 前台用户信息
    protected $user = null;

    // 初始化
    protected function initialize()
    {

        // 后台用户
        if (Session::get('token') || cookie('token')) {

            $token = cookie('token') ? cookie('token') : Session::get('token');
           
            $this->admin = Admin::checkToken($token);
            View::assign('admin',$this->admin);
            AdminLog::write($this->admin);  // 记录后台行为日志
        $group = AuthGroup::findGroup($this->admin->id);
        $ids = explode(',',$group['rules']);
        // 左侧菜单
        $menus = \app\model\Base::getMenus($ids);
        View::assign(['menus'=>$menus]);
        }
         //游客记录
        $data = Index::touristRecords();
        View::assign('tourist',$data['tourist_name']);
        // 前台用户
        if (Session::get('userToken') || cookie('userToken')){
            $userToken = cookie('userToken') ?: Session::get('userToken');
            $this->user = User::checkToken($userToken);
        }
        $id = isset($this->user['id']) ? $this->user['id'] : 0;
        View::assign('list',lineTime($id));
        View::assign('user',$this->user);
        // 渲染视图栏目(已缓存)
        View::assign('cat',$this->tree(Category::getCategory(),0,0));
        // 轮播图(已缓存)
        View::assign('banner',Banner::banner());
        // 导航
        View::assign('sidebar',Sidebar::sidebar());
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}