<?php
/**
 * +----------------------------------------------------------------------
 * | 九月科技-ztuc.cn
 * +----------------------------------------------------------------------
 *                      .::::.
 *                    .::::::::.            | AUTHOR: siyu
 *                    :::::::::::           | EMAIL: ztucke@ztuc.cn
 *                 ..:::::::::::'           | DATETIME: 2020/01/31
 *             '::::::::::::'
 *                .::::::::::
 *           '::::::::::::::..
 *                ..::::::::::::.
 *              ``::::::::::::::::
 *               ::::``:::::::::'        .:::.
 *              ::::'   ':::::'       .::::::::.
 *            .::::'      ::::     .:::::::'::::.
 *           .:::'       :::::  .:::::::::' ':::::.
 *          .::'        :::::.:::::::::'      ':::::.
 *         .::'         ::::::::::::::'         ``::::.
 *     ...:::           ::::::::::::'              ``::.
 *   ```` ':.          ':::::::::'                  ::::..
 *                      '.:::::'                    ':'````..
 * +----------------------------------------------------------------------
 */

return [
    'Sensitive words'                             => '请输入',
    'Support fuzzy search'                             => '支持模糊搜索敏感词',
    'Created on'                                  => '创建时间：',
    'query'                                       => '查询',
    'Submit for verification'                     => '提交验证',
    'Sending, please wait'                        => '发送中，请稍候',
    'Verification in progress, please wait'       => '验证中，请稍候',
    'Login, please wait'                          => '登录中，请稍候',
    'Submitting, please wait'                     => '提交中，请稍候',
    'Registration, please wait'                   => '注册中，请稍候',
    'Modifying, please wait'                      => '修改中，请稍候',
    'Please enter the verification code'          => '请输入验证码',
    'Please select a line'                        => '请选择一行！',
    'Please enter the login password'             => '请输入登录密码',
    'enter one user name'                         => '请输入用户名',
    'Please input email'                          => '请输入邮箱',
    'Please enter a new phone number'             => '请输入新手机号',
    'Please enter a new email'                    => '请输入新邮箱',
    'Please input the content'                    => '请输入内容',
    'Please input a password'                     => '请输入密码',
    'mailbox'                                     => '邮 箱',
    'Mobile'                                      => '手 机',
    'Resend'                                      => '重 发',
    'Batch delete'                                => '批量删除',
    'delete'                                      => '删除',
    'newly added'                                 => '新增',
    'Refresh'                                     => '刷新',
    'edit'                                        => '编辑',
    'preservation'                                => '保存',
    'cancel'                                      => '取消',
    'Points consumed in each lottery'             => '每次抽奖消耗积分',
    'Sign out'                                    => '注 销',
    'Lottery probability'                         => '抽奖概率',
    'Number of lucky draw per person per day'     => '每人每天抽奖次数',
    'Prize Title'                                 => '奖品标题：',
    'Please select Delete item'                   => '请选择删除项！',
    'Really delete it'                            => '真的删除么？',
    'Responsive display of complex combination of mobile device, tablet and desktop'                             
                                                  => '移动设备、平板、桌面端的复杂组合响应式展现',
    'Upload Avatar'                               => '上传头像',
    'Upload pictures'                             => '上传图片',
    'pictures'                                    => '图片',
    'Carousel map'                                => '轮播图',
    'Please select'                               => '请选择:',
    'Sina email'                                  => '新浪',
    'Enterprise mailbox'                          => '腾讯',
    'Box 126'                                     => '网易',
    'Tencent SMS'                                     => '腾讯短信',
    'Permission group'                            => '权限组',
    'Log out'                                     => '注销登录',
    'First name'                                  => '名 称',
    'Mailbox'                                     => '邮 箱',
    'User name is required. How can it be empty'  => '用户名是必填项，岂能为空？',
    'password'                                    => '密 码',
    'Change Password'                             => '修改密码',
    'normal'                                      => '正常',
    'locking'                                     => '锁定',
    'Upload failed'                               => '上传失败',
    'retry'                                       => '重试',
    'author'                                      => '作者',
    'title'                                       => '标题',
    'Column'                                      => '所属栏目',
    'content'                                     => '内容',
    'key word'                                    => '关键词',
    'New email address'                           => '点赞量',
    'Views'                                       => '浏览量',
    'No data available'                           => '无可用数据',
    'User data table'                             => '用户数据表',
    'Please select'                               => '请选择',
    'sign'                                        => '标志',
    'newest'                                      => '最新',
    'Hot'                                         => '热门',
    'recommend'                                   => '推荐',
    'sort'                                        => '排序',
    'Please input sort'                           => '请输入排序',
    'Top'                                         => '置顶',
    'Group name'                                  => '组名',
    'Menu permissions'                            => '菜单权限',
    'state'                                       => '状 态',
    'open'                                        => '开启',
    'close'                                       => '关闭',
    'Double click to save'                        => '双击保存',
    'Please select the menu'                      => '请选择菜单',
    'head portrait'                               => '头像',
    'Parent'                                      => '父级',
    'nothing'                                     => '无',
    'route'                                       => '路由',
    'small icons'                                 => '小图标',
    'Menu'                                        => '菜 单',
    'display'                                     => '显示',
    'hide'                                        => '隐藏',
    'describe'                                    => '描述',
    'Jump link'                                   => '跳转链接',
    'Verification Code'                           => '验证码:',
    'Template'                                    => '模 板',
    'Please input column name'                    => '请输入栏目名称',
    'waterfall'                                   => '瀑布',
    'Gongge'                                      => '宫格',
    'Chat content'                                => '聊天内容：',
    'Chat record'                                 => '聊天记录',
    'Comments'                                    => '评论词：',
    'Comment content'                             => '评论内容',
    'Expiration time'                             => '过期时间',
    'Winning probability of single prize'         => '单个奖品中奖概率',
    'Prize details'                               => '奖品明细',
    'Prize Title'                                 => '奖品标题：',
    'see'                                         => '查看',
    'Disable'                                     => '禁用',
    'user name'                                   => '用户名',
    'Member IP'                                   => '会员IP',
    'Number of return visits'                     => '回访次数',
    'on-line'                                     => '在线',
    'off-line'                                    => '离线',
    'wipe data'                                   => '清空数据',
    'phone'                                       => '手机号',
    'Parameter configuration'                     => '参数配置',
    'Member'                                      => '会员',
    
    'Administrator login'                         => '管理员登录',
    'identity authentication'                     => '身份认证',
    'Click send'                                  => '点击发送',
    'Submit for verification'                     => '提交验证',
    'Trust current device, no need to verify within 7 days'                   
                                                  => '信任当前设备，7天内无需验证',
    'Sending, please wait'                        => '发送中，请稍候',
    'Verification in progress, please wait'       => '验证中，请稍候',
    'Login, please wait'                          => '登录中，请稍候',
    'Submitting, please wait'                     => '提交中，请稍候',
    'Registration, please wait'                   => '注册中，请稍候',
    'Modifying, please wait'                      => '修改中，请稍候',
    'Binding, please wait'                        => '绑定中，请稍候',
    'Re signing, please wait'                        => '补签中，请稍候',
    'Please wait while we sign in'                        => '签到中，请稍候',
    'Please enter the verification code'          => '请输入验证码',
    'Please input user name / email / mobile number' 
                                                  => '请输入用户名/邮箱/手机号',
    'Please enter the login password'             => '请输入登录密码',
    'enter one user name'                         => '请输入用户名',
    'Please input email'                          => '请输入邮箱',
    'Please enter a new phone number'             => '请输入新手机号',
    'Please input mobile phone number'             => '请输入手机号',
    'Please enter a new email'                    => '请输入新邮箱',
    'Please input sort'                           => '请输入排序',
    'Please input the content'                    => '请输入内容',
    'mailbox'                                     => '邮 箱',
    'Mobile'                                      => '手 机',
    'Resend'                                      => '重 发',
    'User registration'                           => '用户注册',
    'User login'                                  => '用户登录',
    'Sign out'                                    => '注 销',
    'second'                                      => '秒',
    'Authentication enabled'                      => '已开启身份认证',
    'Remember to log in'                          => '记住登录',
    'Forget the password'                         => '忘记密码',
    'Sign in now'                                 => '立即登录',
    'Register now'                                => '立即注册',
    'Email retrieval'                             => '邮箱找回',
    'SMS retrieval'                               => '短信找回',
    'Membership Center'                           => '会员中心',
    'Log out'                                     => '注销登录',
    'home page'                                   => '首页',
    'Contribution zone'                           => '投稿专区',
    'My sign in'                                  => '我的签到',
    'personal data'                               => '个人资料',
    'Message zone'                                => '留言专区',
    'Change Password'                             => '修改密码',
    'Lottery turntable'                           => '抽奖转盘',
    'Click Edit'                                  => '点击编辑',
    'Edit'                                        => '编辑',
    'Member'                                      => '会 员',
    'QQ'                                          => 'Q  Q',
    'brief introduction'                          => '简 介',
    'Introduce yourself in one sentence'          => '一句话介绍一下你自己',
    'modify'                                      => '修改',
    'preservation'                                => '保存',
    'Please select:'                              => '请选择:',
    'New email address:'                          => '新邮箱:',
    'Verification Code:'                          => '验证码:',
    'obtain'                                      => '获 取',
    'Submit'                                      => '提 交',
    'New mobile phone:'                           => '新手机:',
    'Upload failed'                               => '上传失败',
    'retry'                                       => '重试',
    'Signed in'                                   => '已签到',
    'No sign in'                                  => '未签到',
    'Sign in'                                     => '签到',
    'head portrait'                               => '头像',
    'Please go to personal data binding mailbox to retrieve the password!'                                     
                                                  => '请去Personal Data绑定邮箱，找回密码需要用到！',
    'QQ quick login'                              => 'QQ快捷登录',
    'Bound'                                       => '已绑定',
    'Change the binding'                          => '换绑',
    'Unbound'                                     => '未绑定',
    'binding'                                     => '绑定',
    'Grade'                                       => '等级',
    'level'                                       => '级',
    'balance'                                     => '余额',
    'element'                                     => '元',
    'integral'                                    => '积分',
    'Continuous login days'                       => '连续登录天数',
    'Maximum login days'                          => '最大登录天数',
    'day'                                         => '天',
    'login time'                                  => '登录时间',
    'Remaining login time'                        => '剩余登录时间',
    'Insist on signing in, surprise'              => '坚持签到，有惊喜',
    'pictures'                                    => '图片',
    'Upload pictures'                             => '上传图片',
    'Column'                                      => '所属栏目',
    'Please select'                               => '请选择',
    'author'                                      => '作者',
    'title'                                       => '标题',
    'content'                                     => '内容',
    'key word'                                    => '关键词',
    'Keywords, separated by commas'               => '关键词,以逗号分隔',
    'sign'                                        => '标志',
    'newest'                                      => '最新',
    'Hot'                                         => '热门',
    'recommend'                                   => '推荐',
    'sort'                                        => '排序',
    'cancel'                                      => '取消',
    'Please input'                                => '请输入',
    'Leaving a message.'                          => '留言',
    'tourist'                                     => '游客',
    'Total chat comments'                         => '共有%a条记录',
    'Comment list'                                => '评论列表',
    'Old password'                                => '旧密码',
    'New password'                                => '新密码',
    'Confirm password'                            => '确认密码',
    'Refill'                                      => '重填',
    'User binding'                                => '用户绑定',
    'QQ authorization successful!'                => 'QQ授权成功！',
    'Hello!'                                      => '您好',
    'Sign in points rule'                         => '签到积分规则',
    'Ranking List'                                => '排行榜',
    'Continue to sign in'                         => '你当前已经连续签到 %a 天、 明天继续签到可获得 %b 积分',
    'Check in today'                              => '今天签到可获得 %a 积分，请点击签到领取积分',
    'Confirm the date of supplementary signature' => '确认进行补签日期',
    'Additional signature will consume'           => '补签将消耗',
    'Continuous check in days'                    => '连续签到天数',
    'Get points'                                  => '获得积分',
    'Nickname?'                                   => '昵称',
    'Continuous attendance'                       => '连续签到',
    'read'                                        => '阅读',
    'comment'                                     => '评论',
    'give the thumbs-up'                          => '点赞',
    'Yes'                                         => '已赞',
    'Next'                                        => '下一篇',
    'Last'                                        => '上一篇',
    'Read'                                        => '已读',
    'Unread'                                        => '未读',
    'All set read'                                        => '全设未读',
    'All unread'                                        => '全设已读',
    'determine'                                   => '确定',
    'This page will be re-directed in %s seconds' => '页面将在 %s 秒后自动跳转'
];
